USE ROLE ACCOUNTADMIN;

-- 1. Role
CREATE ROLE IF NOT EXISTS OPENFLOW_ADMIN
  COMMENT = 'Openflow DAG Factory admin role — manages flows, connectors, secrets, runtimes';


-- 2. Warehouse
CREATE WAREHOUSE IF NOT EXISTS OPENFLOW_FACTORY_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse used by the openflow-dag-factory backend';


GRANT USAGE, OPERATE ON WAREHOUSE OPENFLOW_FACTORY_WH TO ROLE OPENFLOW_ADMIN;

-- 3. Database + schemas
CREATE DATABASE IF NOT EXISTS OPENFLOW_FACTORY
  COMMENT = 'Metadata, secrets, and audit log for openflow-dag-factory';


GRANT USAGE, MONITOR ON DATABASE OPENFLOW_FACTORY TO ROLE OPENFLOW_ADMIN;
GRANT CREATE SCHEMA ON DATABASE OPENFLOW_FACTORY TO ROLE OPENFLOW_ADMIN;

CREATE SCHEMA IF NOT EXISTS OPENFLOW_FACTORY.METADATA;
CREATE SCHEMA IF NOT EXISTS OPENFLOW_FACTORY.SECRETS;

GRANT USAGE, MODIFY, MONITOR,
    CREATE TABLE, CREATE VIEW, CREATE STAGE,
    CREATE FUNCTION, CREATE PROCEDURE, CREATE TASK
    ON SCHEMA OPENFLOW_FACTORY.METADATA TO ROLE OPENFLOW_ADMIN;

GRANT USAGE, MODIFY, MONITOR,
      CREATE SECRET, CREATE NETWORK RULE
      ON SCHEMA OPENFLOW_FACTORY.SECRETS TO ROLE OPENFLOW_ADMIN;

-- 4. Account-level grants (Openflow runtime + EAI management)
GRANT CREATE DATABASE ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE INTEGRATION   ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE NETWORK POLICY ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT EXECUTE TASK   ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE OPENFLOW_ADMIN;



-- 5. Service user (replace the public key)
CREATE USER IF NOT EXISTS OPENFLOW_FACTORY_SVC
  TYPE = SERVICE
  RSA_PUBLIC_KEY = '<YOUR-RSA-KEY>'
  DEFAULT_ROLE = OPENFLOW_ADMIN
  DEFAULT_WAREHOUSE = OPENFLOW_FACTORY_WH
  DEFAULT_NAMESPACE = OPENFLOW_FACTORY.METADATA
  COMMENT = 'Backend service account for openflow-dag-factory';

GRANT ROLE OPENFLOW_ADMIN TO USER OPENFLOW_FACTORY_SVC;
GRANT ROLE OPENFLOW_ADMIN TO USER IDENTIFIER(CURRENT_USER());



-- ============================================================================
-- Deployment Log — lives in OPENFLOW_FACTORY.METADATA
-- Tracks what was deployed, enabling idempotency (same sha = no-op).
-- ============================================================================


CREATE TABLE IF NOT EXISTS OPENFLOW_FACTORY.METADATA.DEPLOYMENT_LOG (
    id                STRING NOT NULL DEFAULT UUID_STRING(),
    runtime_name      STRING NOT NULL,
    contract_paths    ARRAY NOT NULL,
    template_id       STRING,
    template_version  STRING,
    contract_sha      STRING NOT NULL,
    deployed_at       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    process_group_id  STRING,
    PRIMARY KEY (id)
);

CREATE OR REPLACE VIEW OPENFLOW_FACTORY.METADATA.LATEST_DEPLOYMENTS AS
SELECT *
FROM OPENFLOW_FACTORY.METADATA.DEPLOYMENT_LOG
QUALIFY ROW_NUMBER() OVER (PARTITION BY runtime_name ORDER BY deployed_at DESC) = 1;